name: Fitness
favicon: null
layout_spectrum: 0.37828710419125855
typography_spectrum: 0.6551061025820673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3740832156036049
  lightness: 0.6720553941559047
  saturation: 0.6341691100969911
  rhythmicContrast: 0.6308615987654775
purpose: []
